---
abstract: 'Perl class to communication with morph.io.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-MorphIO
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Class::Utils: 0.05
  Error::Pure: 0.16
  IO::Barf: 0.07
  LWP::Simple: 0
  URI: 0
  URI::Escape: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=WebService-MorphIO
  homepage: https://github.com/tupinek/WebService-MorphIO
  license: http://opensource.org/licenses/BSD-3-Clause
  repository: git://github.com/tupinek/WebService-MorphIO
version: 0.01
